### ISSUE TITLE
[Pathfinding] Bug

### ISSUE THREAD

**Issue by Hazurl** [leek-wars/leek-wars-generator-next#17]
![Report](http://i.imgur.com/KiUGATt.png)
It's not the shortest path.

**Comment by Hazurl** [comment]
Other examples : ![Map Report](http://i.imgur.com/k73ilM8.png)
![Map Report](http://i.imgur.com/HxBrUSz.png)

**Comment by 5pilow** [comment]
Oui je suis au courant de ce problème, après le but n'est pas forcément d'obtenir le chemin le plus court

**Comment by 5pilow** [comment]
Ça devrait être bon maintenant !
