### ISSUE TITLE
Impossible de compiler leek-wars-generator

### ISSUE THREAD

**Issue by coucougithub** [leek-wars/leek-wars-generator-next#25]
Bonjour,

Je voudrais faire fonctionner leekwars sur mon PC pour tester un algo de reinforcement learning.
Je n'ai pas de soucis pour construire le leekscript, par contre le leek wars generator affiche des problèmes dont quelques exemples sont donnés ci-dessous. 

last_exception is not a member of ls::VM
ls::Nature has not been declared
...

J'ai l'impression que les sources présentes dans ce repo correspondent à une ancienne version du leekscript, existe-t-il une mise à jour du leek-wars-generator ?

**Comment by 5pilow** [comment]
Bonjour,
Non malheuresement le dépôt leek-wars-generator n'est pas à jour par rapport au leekscript :/
Je vais le faire après avoir stabilisé la nouvelle version du leekscript qui est passé de LibJIT à LLVM.

Après il faut savoir que le leekscript (v2) sur GitHub n'est pas celui qui tourne sur Leek Wars actuellement (v1). Donc ce que tu codes ne pourrait pas vraiment s'appliquer sur le jeu réel.

**Comment by coucougithub** [comment]
Bonsoir,

Merci pour ta réponse, c'est plus clair. Aurais tu un exemple d'un commit du leekscript utilisable en V1 ou presque ?

Je ne cherche pas à performer sur Leek Wars, mais à pratiquer le machine learning et j'ai été emballé par le principe de leekwars pour ce faire ! Merci pour le beau boulot !

**Comment by 5pilow** [comment]
La version v1 du LeekScript n'est pas sur GitHub malheureusement, ça arrivera peut être plus tard quand la v2 aura complètement remplacé la v1.

Merci à toi !
